# Generated by Django 3.1.6 on 2021-02-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='tag',
            field=models.ManyToManyField(blank=True, to='produit.Tag'),
        ),
    ]
