# Generated by Django 3.1.6 on 2021-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeLocataire',
        ),
        migrations.AddField(
            model_name='account',
            name='typelocataire',
            field=models.CharField(choices=[('PART', 'Particulier'), ('PROF', 'Profesionnel')], default='PART', max_length=4, verbose_name='Type de loueur'),
        ),
    ]
