# Generated by Django 3.1.6 on 2021-03-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210318_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('rue', models.CharField(blank=True, max_length=20)),
                ('voie', models.CharField(blank=True, max_length=35)),
                ('ville', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('pays', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='code_postal',
        ),
    ]
