# Generated by Django 3.1.6 on 2021-03-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='photo',
            new_name='photo_identite',
        ),
        migrations.AddField(
            model_name='account',
            name='photo_profil',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
