# Generated by Django 3.1.6 on 2021-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210324_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo_stream',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
