# Generated by Django 3.1.6 on 2021-02-24 13:59

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='SalaireFoyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address1',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='client',
            name='address2',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address', verbose_name=''),
        ),
        migrations.AddField(
            model_name='client',
            name='budgetLoyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='address.address', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='address.address', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='client',
            name='document_avis',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 1: Avis d'impot, attestation d'emplyeur ou contrat de travail"),
        ),
        migrations.AddField(
            model_name='client',
            name='document_paye',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 2: 3 dernières fiches de payes, pièces d'identité"),
        ),
        migrations.AddField(
            model_name='client',
            name='document_quittance',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Pièce 3: 3 dernières quittance de loyers'),
        ),
        migrations.AddField(
            model_name='client',
            name='lieuRecherche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='motifDemenag',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='package_choice',
            field=models.CharField(choices=[('PDOS', 'Pack Dossier'), ('PVST', 'Pack Visite'), ('PBAS', 'Pack Basique'), ('PBST', 'Pack Booster'), ('PPRE', 'Pack Premium'), ('PCNC', 'Pack Conciergerie')], default='PDOS', max_length=4, verbose_name='Confirmer votre pack'),
        ),
        migrations.AddField(
            model_name='client',
            name='personne_foyer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de personnes dans le foyer'),
        ),
        migrations.AddField(
            model_name='client',
            name='postalCode',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localities_country', to='address.address', verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='client',
            name='precisRecherche',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='referent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='situation_matrimo',
            field=models.CharField(choices=[('MARR', 'Marrié (e)'), ('DIVO', 'Divorcé (e)'), ('CELI', 'Célibataire'), ('SEPA', 'Séparé (e)'), ('VEUF', 'Veuf (ve)')], default='CELI', max_length=4, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='client',
            name='typeBien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
