# Generated by Django 3.1.6 on 2021-02-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('hebergement_choice', models.CharField(choices=[('APPT', 'Appartemment'), ('MAIS', 'Maison'), ('STUD', 'Studio'), ('OTHR', 'Autre')], default='APPT', max_length=4, verbose_name="Type d'hébergement")),
                ('type_location_choices', models.CharField(choices=[('ENTR', 'Logement entier'), ('PRIV', 'Chambre privée'), ('PART', 'Chambre partagée')], default='ENTR', max_length=4, verbose_name='Location partielle ou totale')),
                ('categorie_logement', models.CharField(max_length=50)),
            ],
        ),
    ]
