# Generated by Django 3.1.6 on 2021-02-26 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_auto_20210225_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='pieces_couchage',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='annonce',
            name='titre_logement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie_logement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='annonce',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='annonce.Equipements'),
        ),
    ]
