# Generated by Django 3.1.6 on 2021-02-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0004_auto_20210226_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='equipements',
            field=models.ManyToManyField(to='annonce.Equipements'),
        ),
    ]
