# Generated by Django 3.1.6 on 2021-03-08 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0005_auto_20210226_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='nombre_personne',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='annonce.Equipements'),
        ),
    ]
