# Generated by Django 3.1.6 on 2021-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0009_auto_20210309_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='charges_loyer',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='loyer_tc',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='charges',
            field=models.ManyToManyField(blank=True, to='annonce.Charges'),
        ),
    ]
