# Generated by Django 3.1.6 on 2021-03-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0011_annonce_photos_loyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='photos_loyer',
        ),
        migrations.CreateModel(
            name='ImageLogement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.annonce')),
            ],
        ),
    ]
