# Generated by Django 3.1.6 on 2021-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0014_auto_20210315_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='caledrier_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='calendrier_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
