# Generated by Django 3.1.6 on 2021-03-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0015_auto_20210315_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendrier',
            old_name='caledrier_debut',
            new_name='calendrier_debut',
        ),
    ]
