# Generated by Django 3.1.6 on 2021-03-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0016_auto_20210315_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendrier',
            old_name='disponibilité',
            new_name='disponibilite',
        ),
    ]
