# Generated by Django 3.1.6 on 2021-03-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0017_auto_20210315_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='annonce.annonce')),
                ('heure_arrivee_apres', models.CharField(choices=[('12h00', 'heure'), ('12h30', 'heure'), ('13h00', 'heure'), ('13h30', 'heure'), ('14h00', 'heure'), ('14h30', 'heure'), ('15h00', 'heure'), ('15h30', 'heure'), ('16h00', 'heure'), ('16h30', 'heure'), ('17h00', 'heure'), ('17h30', 'heure'), ('18h00', 'heure'), ('18h30', 'heure'), ('19h00', 'heure'), ('19h30', 'heure'), ('20h00', 'heure')], default='flexible', max_length=10, verbose_name="Heure d'arrivée(après)")),
                ('heure_arrivee_avant', models.CharField(choices=[('14h00', 'heure'), ('14h30', 'heure'), ('15h00', 'heure'), ('15h30', 'heure'), ('16h00', 'heure'), ('16h30', 'heure'), ('17h00', 'heure'), ('17h30', 'heure'), ('18h00', 'heure'), ('18h30', 'heure'), ('19h00', 'heure'), ('19h30', 'heure'), ('20h00', 'heure'), ('20h30', 'heure'), ('21h00', 'heure'), ('21h30', 'heure'), ('22h00', 'heure')], default='flexible', max_length=10, verbose_name="Heure d'arrivée(avant)")),
                ('heure_depart', models.CharField(choices=[('9h00', 'heure'), ('9h30', 'heure'), ('10h00', 'heure'), ('10h30', 'heure'), ('11h00', 'heure'), ('11h30', 'heure'), ('12h00', 'heure'), ('12h30', 'heure'), ('13h00', 'heure'), ('13h30', 'heure'), ('14h00', 'heure'), ('14h30', 'heure'), ('15h00', 'heure'), ('15h30', 'heure'), ('16h00', 'heure'), ('16h30', 'heure'), ('17h00', 'heure'), ('17h30', 'heure'), ('18h00', 'heure')], default='flexible', max_length=10, verbose_name='Heure de départ(avant)')),
                ('accessible_handicape', models.BooleanField(choices=[(1, 'Oui'), (2, 'Non')], default=2)),
                ('fumeur_accepte', models.BooleanField(choices=[(1, 'Oui'), (2, 'Non')], default=2)),
                ('animaux_accepte', models.BooleanField(choices=[(1, 'Oui'), (2, 'Non')], default=2)),
            ],
        ),
    ]
