# Generated by Django 3.1.6 on 2021-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0022_auto_20210317_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fumee', models.BooleanField(default=False, verbose_name='Détecteur de fumée')),
                ('carbone', models.BooleanField(default=False, verbose_name='Détecteur de monoxyde de carbone')),
                ('extincteur', models.BooleanField(default=False, verbose_name='Extincteur')),
            ],
        ),
    ]
