# Generated by Django 3.1.6 on 2021-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0026_auto_20210317_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='amianteDoc',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='copopriete',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='interieurElecGaz',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='risqueNaturel',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='risquePlomb',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
