# Generated by Django 3.1.6 on 2021-03-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0027_auto_20210318_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAnnonce',
            fields=[
                ('account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='annonce.annonce')),
                ('rue', models.CharField(blank=True, max_length=20)),
                ('voie', models.CharField(blank=True, max_length=35)),
                ('ville', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('pays', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='address',
        ),
    ]
