# Generated by Django 3.1.6 on 2021-04-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0028_auto_20210331_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressAnnonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(blank=True, max_length=20)),
                ('voie', models.CharField(blank=True, max_length=35)),
                ('ville', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('pays', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='annonce',
            name='dureeLocationMaxi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='dureeLocationMini',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AddressAnnonce',
        ),
        migrations.AddField(
            model_name='annonce',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonce.adressannonce'),
        ),
    ]
