# Generated by Django 3.1.6 on 2021-04-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0029_auto_20210402_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageLogement',
        ),
    ]
