# Generated by Django 3.1.6 on 2021-04-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0031_auto_20210406_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='images',
        ),
        migrations.DeleteModel(
            name='PhotosLogement',
        ),
    ]
