# Generated by Django 3.1.6 on 2021-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0033_imagelogement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='services',
            field=models.ManyToManyField(blank=True, to='annonce.Services'),
        ),
    ]
