# Generated by Django 3.1.6 on 2021-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0034_auto_20210517_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='categorie',
            field=models.CharField(choices=[('life', 'Lifestyle'), ('bien', 'Bien être'), ('quot', 'Services quotidiens'), ('lois', 'Loisirs'), ('trsp', 'Transports'), ('inst', 'Installation')], default='life', max_length=4, verbose_name='Categorie Service'),
        ),
    ]
