# Generated by Django 3.1.6 on 2021-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0036_auto_20210518_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieservice',
            name='service_checked',
            field=models.BooleanField(default=False),
        ),
    ]
