# Generated by Django 3.1.6 on 2021-06-02 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonce', '0038_remove_categorieservice_service_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reserved', to=settings.AUTH_USER_MODEL),
        ),
    ]
