# Generated by Django 3.1.6 on 2021-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0039_annonce_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
