# Generated by Django 3.1.6 on 2021-02-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkboxcourse1',
            fields=[
                ('cb1_id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename1', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'check box courses',
                'db_table': 'CheckBox1_Cli',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SignerCli',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('cli_prenom', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('cli_email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('cli_document_avis', models.FileField(null=True, upload_to='documents/', verbose_name="Pièce 1: Avis d'impot, attestation d'emplyeur ou contrat de travail")),
            ],
            options={
                'verbose_name': 'SignerClient',
                'db_table': 'Signer_Cli',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='clientcli',
            name='cli_referent',
            field=models.CharField(max_length=100, null=True, verbose_name='Referent'),
        ),
        migrations.CreateModel(
            name='checkboxcourses',
            fields=[
                ('cb_id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('cli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='soumission.clientcli', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'check box courses',
                'db_table': 'CheckBox_Cli',
                'managed': True,
            },
        ),
    ]
