# Generated by Django 3.1.6 on 2021-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='File',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
