# Generated by Django 3.1.6 on 2021-03-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_file_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Files',
        ),
    ]
