# Generated by Django 3.1.6 on 2021-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20210309_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('s_name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('File', models.FileField(max_length=255, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
