# Generated by Django 3.1.6 on 2021-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_remove_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='File',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
