# Generated by Django 3.1.6 on 2021-03-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20210311_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalFile',
        ),
    ]
