# Generated by Django 3.1.6 on 2021-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20210311_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='File_id',
        ),
        migrations.AddField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
