# Generated by Django 3.1.6 on 2021-03-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_file_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='verdict',
        ),
    ]
