# Generated by Django 3.1.6 on 2021-03-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_file_verdict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='File',
            new_name='my_file',
        ),
    ]
