# Generated by Django 3.1.6 on 2021-04-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20210328_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdressWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(blank=True, max_length=20)),
                ('voie', models.CharField(blank=True, max_length=35)),
                ('ville', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=20)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('pays', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='file',
            name='my_file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='s_name',
        ),
        migrations.AddField(
            model_name='file',
            name='SalaireFoyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='budgetLoyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='document_avis',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 1: Avis d'impot, attestation d'emplyeur ou contrat de travail"),
        ),
        migrations.AddField(
            model_name='file',
            name='document_paye',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 2: 3 dernières fiches de payes, pièces d'identité"),
        ),
        migrations.AddField(
            model_name='file',
            name='document_quittance',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Pièce 3: 3 dernières quittance de loyers'),
        ),
        migrations.AddField(
            model_name='file',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='lieuRecherche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='motifDemenag',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='package_choice',
            field=models.CharField(choices=[('PDOS', 'Pack Dossier'), ('PVST', 'Pack Visite'), ('PBAS', 'Pack Basique'), ('PBST', 'Pack Booster'), ('PPRE', 'Pack Premium'), ('PCNC', 'Pack Conciergerie')], default='PDOS', max_length=4, verbose_name='Confirmer votre pack'),
        ),
        migrations.AddField(
            model_name='file',
            name='personne_foyer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de personnes dans le foyer'),
        ),
        migrations.AddField(
            model_name='file',
            name='precisRecherche',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='referent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='situation_matrimo',
            field=models.CharField(choices=[('MARR', 'Marrié (e)'), ('DIVO', 'Divorcé (e)'), ('CELI', 'Célibataire'), ('SEPA', 'Séparé (e)'), ('VEUF', 'Veuf (ve)')], default='CELI', max_length=4, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='file',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='typeBien',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='verdict',
            field=models.CharField(choices=[('acct', 'Accepté'), ('attn', 'Attente'), ('refu', 'Refusé')], default='refu', max_length=4, verbose_name='Verdict'),
        ),
        migrations.AddField(
            model_name='file',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.adressworkflow'),
        ),
    ]
