# Generated by Django 3.1.6 on 2021-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_file_type_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type_visite',
            field=models.CharField(choices=[('0', 'Visites substituées'), ('1', 'Visites physiques')], max_length=30, null=True),
        ),
    ]
