# Generated by Django 3.1.6 on 2021-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_file_planificateur_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
    ]
