# Generated by Django 3.1.6 on 2021-05-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20210422_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire_demeya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire_nek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='commentaire_demaya',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.commentaire_demeya'),
        ),
        migrations.AddField(
            model_name='file',
            name='commentaire_nek',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.commentaire_nek'),
        ),
    ]
