# Generated by Django 3.1.6 on 2021-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20210503_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='commentaire_demaya',
        ),
        migrations.AddField(
            model_name='file',
            name='commentaire_demaya',
            field=models.ManyToManyField(null=True, to='workflow.Commentaire_demeya'),
        ),
        migrations.RemoveField(
            model_name='file',
            name='commentaire_nek',
        ),
        migrations.AddField(
            model_name='file',
            name='commentaire_nek',
            field=models.ManyToManyField(null=True, to='workflow.Commentaire_nek'),
        ),
    ]
