# Generated by Django 3.1.6 on 2021-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_auto_20210504_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_reunion',
            field=models.DateTimeField(null=True),
        ),
    ]
