# Generated by Django 3.1.6 on 2021-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_file_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='bilan_semaine',
            field=models.ManyToManyField(null=True, to='workflow.Bilan'),
        ),
    ]
